import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import BottomNav from "@/components/BottomNav"
import { ThemeProvider } from "@/components/theme-provider"
import Header from "@/components/Header";
import { cn } from "@/lib/utils"


const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased py-14 ",
        fontSans.variable
      )}>

        <Header />

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

          {children}



          <BottomNav />
        </ThemeProvider>


      </body>
    </html>
  );
}
